# Generated by Django 5.0.6 on 2024-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('Contest_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
            ],
        ),
    ]
