# Generated by Django 5.0.6 on 2024-06-30 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='Participants',
            field=models.ManyToManyField(null=True, related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contests',
            name='Questions',
            field=models.ManyToManyField(related_name='contests', to='question.questions'),
        ),
    ]
