# Generated by Django 5.0.6 on 2024-07-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contests',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
