# Generated by Django 5.0.6 on 2024-07-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_remove_score_user_score_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
