# Generated by Django 5.0.6 on 2024-06-30 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('question_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('Tag', models.CharField(max_length=100)),
                ('Difficulty', models.CharField(max_length=10)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='testcases',
            fields=[
                ('Test_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Input', models.TextField()),
                ('Output', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='question.questions')),
            ],
        ),
    ]
