# Generated by Django 5.0.6 on 2024-07-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
